---
title: "car 資料-網路上汽車銷售資料"
output:
  html_document:
    df_print: paged
---
**id**	the (unique) identifier for the post

**title**	a short text description for the post

**body**	the full free-form text for the post

**lat**, **long**	the longitude and latitude associated with the post, i.e., that of the poster or of the location of the car, or both.

**posted**	the date the post was originally posted

**updated**	the date of the most recent modification to the post

**drive**	what type of drive the vehicle has, e.g., front-wheel drive.

**odometer**	the number of miles on the car's odometer里程表.

**type**	what type of vehicle is the post about, e.g., car, van, truck.

**header**	a shot description for the post, different from the body, and potentially different form the title.

**condition**	a description of what condition the vehicle is in, e.g., excellent

**cylinders**	the number of cylinders in the vehicle's engine. 引擎缸數

**fuel**	the type of fuel the vehicle uses, e.g., gas

**size**	a categorical description of the size of the vehicle, e.g., compact, mid-size.

**transmission**	the transmission type of the vehicle, e.g., automatic, manual.

**byOwner**	a logical value with TRUE indicating the vehicle is being sold by its owner, not a dealer

**city**	the city on whose bulletin board the post was submitted

**time**	the date and time when the post was posted

**description**	a short description for the post

**location**	the user-supplied city/town for the post

**url**	part of the URL for the post

**price**	the price being sought for the vehicle

**year**	the year the car was manufactured

**maker**	the name of the car manufacturer, e.g., ford, chevrolet. These are extracted from the header or title of the post.

**makerMethod**	a number that identifies which method was used to identify the manufacturer
